### ISSUE TITLE
Setup module should not perform wifi related tasks if setup_wifi is false

### ISSUE THREAD

**Issue by hikinggrass** [EVerest/everest-core#486]
At the moment some wifi related operations are still periodically triggered, even if setup_wifi is set to false in the module config.
This can result in messages like:
```
Failed to connect to non-global ctrl_ifname: <INTERFACE_NAME>  error: Permission denied
```

**Comment by florinmihut** [comment]
This is still happening, we should fix this because it is visible (you just follow the EVerest documentation) and easy to reproduce. Or we should provide the workaround in the documentation:
"Looks Like there's a bug in the setup module where it tries to get some network information even if it's set to false.
In the meantime you could try to remove the setup module from the config-sil, you probably do not need it"
